### PR TITLE
Create petros.json

### PR DESCRIPTION
**Pull request by petroseskinder**
add user into chef.

### CODE REVIEW

**Comment by petroseskinder** [comment]
Should we have different ssh keys?

**Comment by andyfangdz** [comment]
Yeah, otherwise I can login to all your accounts lolz

**Comment by andyfangdz** [comment]
And that I’m not sharing my private key either 😂

**Comment by petroseskinder** [comment]
all right. sounds good. it should be ready for merging

**Comment by petroseskinder** [comment]
@andyfangdz derp moment. i am going to go ahead and merge it.

**Pull request merged**
